Лагутин Владимир Сергеевич ТКИ-141 Задание 3-2 Вариант 17
Kal3s/LagutinVS_TKI-141 pull request #17
Opened 2024-11-11 13:54 UTC by Kal3s

2024-11-11 14:06 UTC, MarinaPaley requested changes
Файл должен быть сохранен в кодировке `UTF-8`

2024-11-11 14:21 UTC, MarinaPaley requested changes

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +}
Убрать

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	for (size_t i = 0; i < epsilon + DBL_EPSILON; ++i) {
по модулю

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		summ = current;
поменять местами

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	double current = 0;
почему 0?

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		current += get_reccurent(i);
+=

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		current += get_reccurent(i);
+=

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		summ = current;
summ += current;

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		summ = current;
`summ += current;`

2024-11-11 14:21 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +int main(void) {
Документация

2024-11-11 14:42 UTC, MarinaPaley requested changes

2024-11-11 14:42 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	return 1.0 / ((k + 3) * (k + 4));
знакопеременный ряд

2024-11-11 14:42 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	}
Считаете сумму n-1 члена, а нужно n

2024-11-11 15:06 UTC, MarinaPaley requested changes

2024-11-11 15:06 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	for (size_t i = 0; i < fabs(epsilon + DBL_EPSILON); ++i) {
модуль члена

2024-11-11 15:06 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +		current *= get_reccurent(i);
Считаете сумму n-1 члена ряда, а нужно n

2024-11-18 12:05 UTC, BalakinaEP requested changes

2024-11-18 12:05 UTC, BalakinaEP commented on Task3-2/Task3-2.c
> +		current *= get_reccurent(i);
поменять местами

2024-11-18 12:05 UTC, BalakinaEP commented on Task3-2/Task3-2.c
> +	for (size_t i = 0; fabs(current) < (epsilon + DBL_EPSILON); ++i) {
fabs(current) > epsilon - DBL_EPSILON

2024-11-25 12:55 UTC, MarinaPaley approved these changes

2024-11-25 12:55 UTC, MarinaPaley commented on Task3-2/Task3-2.c
> +	return value;
`return (size_t)value;`

2024-12-01 13:46 UTC, merged